# Generated by Django 4.2.7 on 2026-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(choices=[('about', 'О компании'), ('payment-delivery', 'Оплата и доставка'), ('contacts', 'Контакты'), ('wholesale', 'Оптовые продажи'), ('public-offer', 'Публичная оферта')], max_length=50, unique=True, verbose_name='Тип страницы'),
        ),
    ]
