# Generated by Django 4.2.7 on 2026-01-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(choices=[('about', 'О компании'), ('payment-delivery', 'Оплата и доставка'), ('contacts', 'Контакты'), ('wholesale', 'Оптовые продажи'), ('public-offer', 'Не является публичной офертой'), ('privacy-policy', 'Политика конфиденциальности'), ('consent', 'Согласие на обработку персональных данных')], max_length=50, unique=True, verbose_name='Тип страницы'),
        ),
    ]
