# Generated by Django 4.2.7 on 2026-01-28 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_category_options_alter_category_image_and_more'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидает обработки'), ('processing', 'В обработке'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='partners.partner', verbose_name='Партнёр')),
            ],
            options={
                'verbose_name': 'Заказ партнёра',
                'verbose_name_plural': 'Заказы партнёров',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Оптовый товар',
                'verbose_name_plural': 'Оптовые товары (импорт для партнёров)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='PartnerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='partners.partnerorder', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе партнёра',
                'verbose_name_plural': 'Товары в заказе партнёра',
                'ordering': ['added_at'],
            },
        ),
    ]
