# Generated by Django 4.2.7 on 2026-01-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partnerorder_wholesaleproduct_partnerorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorder',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к заказу от партнёра', verbose_name='Комментарий партнёра'),
        ),
    ]
