# Generated by Django 4.2.7 on 2026-01-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_1c_integration_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarpostAPISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(help_text='Логин для входа на Farpost', max_length=255, verbose_name='Логин')),
                ('password', models.CharField(help_text='Пароль (хранится в зашифрованном виде)', max_length=255, verbose_name='Пароль')),
                ('packet_id', models.CharField(help_text='ID пакет-объявления на Farpost', max_length=50, verbose_name='ID пакет-объявления')),
                ('is_active', models.BooleanField(default=True, help_text='Использовать эти настройки для синхронизации', verbose_name='Активен')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_sync_status', models.CharField(blank=True, max_length=50, verbose_name='Статус последней синхронизации')),
                ('last_sync_error', models.TextField(blank=True, verbose_name='Ошибка последней синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки API Farpost',
                'verbose_name_plural': 'Настройки API Farpost',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='onecexchangelog',
            new_name='catalog_one_created_8bbd2c_idx',
            old_name='catalog_one_created_idx',
        ),
        migrations.RenameIndex(
            model_name='onecexchangelog',
            new_name='catalog_one_status_7fb3cb_idx',
            old_name='catalog_one_status_idx',
        ),
        migrations.RenameIndex(
            model_name='onecexchangelog',
            new_name='catalog_one_request_eff87a_idx',
            old_name='catalog_one_request_ip_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_externa_e8c827_idx',
            old_name='catalog_prod_external_id_idx',
        ),
    ]
