# Generated by Django 4.2.7 on 2026-01-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_farpostapisettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Необязательно. Если не указан, будет использовано изображение.', max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='promotions/', verbose_name='Изображение')),
                ('link', models.URLField(blank=True, help_text='Куда ведёт акция (необязательно)', verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Акция / Спец предложение',
                'verbose_name_plural': 'Акции / Спец предложения',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='farpostapisettings',
            name='packet_id',
            field=models.CharField(help_text='ID пакет-объявления на Farpost. Один пакет может содержать тысячи товаров из разных категорий. Можно создать несколько настроек с разными packet_id для разделения товаров по пакетам. ID можно найти в URL пакета: https://www.farpost.ru/personal/goods/packet/{id}/recurrent-update', max_length=50, verbose_name='ID пакет-объявления'),
        ),
    ]
