# Generated by Django 4.2.7 on 2026-01-28 07:06

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_catalog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.category_image_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='farpostapisettings',
            name='packet_id',
            field=models.CharField(help_text='ID пакет-объявления на Farpost. Один пакет может содержать тысячи товаров из разных категорий. Можно создать несколько настроек с разными packet_id для разделения товаров по пакетам. ID можно найти в URL пакета: https://www.farpost.ru/personal/goods/packet/{id}/recurrent-update', max_length=50, verbose_name='ID пакет-объявления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (розница)'),
        ),
    ]
