from django.core.management.base import BaseCommand

from catalog.models import Category


class Command(BaseCommand):
    help = (
        "Отключает/удаляет автосгенерированные обрезанные подкатегории "
        "(например: 'Автономн', 'Топливн', 'Трубк')."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Только показать, что будет изменено, без сохранения в БД.",
        )
        parser.add_argument(
            "--delete",
            action="store_true",
            help="Удалять найденные подкатегории вместо деактивации.",
        )
        parser.add_argument(
            "--include-inactive-parents",
            action="store_true",
            help="Проверять также неактивные родительские категории.",
        )

    @staticmethod
    def _normalize_to_singular(word: str) -> str:
        w = (word or "").strip().lower()
        if not w:
            return w
        if w.endswith("ы") and len(w) > 2:
            return w[:-1]
        if w.endswith("и") and len(w) > 3 and w[-2] not in "аеёиоуыэюя":
            return w[:-1]
        if w.endswith("а") and len(w) > 4 and w[-2] not in "аеёиоуыэюя":
            return w[:-1]
        return w

    @staticmethod
    def _is_autogenerated(child: Category) -> bool:
        child_name = (child.name or "").strip().lower()
        child_kw = (child.keywords or "").strip().lower()
        if not child_name:
            return False
        return (
            child_kw == child_name
            or Command._normalize_to_singular(child_kw) == Command._normalize_to_singular(child_name)
        )

    @staticmethod
    def _looks_like_truncated_name(child_name_lower: str, parent_keywords: list[str]) -> bool:
        if not child_name_lower or " " in child_name_lower:
            return False
        for kw in parent_keywords:
            if kw == child_name_lower:
                continue
            # Если это обычная пара ед./мн. числа, это НЕ обрезок.
            if Command._normalize_to_singular(kw) == child_name_lower:
                continue
            if len(kw) <= len(child_name_lower) + 1:
                continue
            if kw.startswith(child_name_lower):
                # Считаем обрезком только если продолжение идет БЕЗ разделителя.
                # "прокладка гбц" -> не обрезок, "топливные" для "топливн" -> обрезок.
                next_char = kw[len(child_name_lower)]
                if not next_char.isalpha():
                    continue
                return True
        return False

    def handle(self, *args, **options):
        dry_run = options["dry_run"]
        delete_mode = options["delete"]
        include_inactive_parents = options["include_inactive_parents"]

        parents_qs = Category.objects.filter(parent__isnull=True)
        if not include_inactive_parents:
            parents_qs = parents_qs.filter(is_active=True)

        affected = []

        for parent in parents_qs:
            parent_keywords = [k.strip().lower() for k in parent.get_keywords_list() if (k or "").strip()]
            if not parent_keywords:
                continue

            children = Category.objects.filter(parent=parent)
            for child in children:
                child_name_lower = (child.name or "").strip().lower()
                if not self._is_autogenerated(child):
                    continue
                if self._looks_like_truncated_name(child_name_lower, parent_keywords):
                    affected.append(child)

        if not affected:
            self.stdout.write(self.style.SUCCESS("Обрезанные автосгенерированные подкатегории не найдены."))
            return

        self.stdout.write(f"Найдено подкатегорий для обработки: {len(affected)}")
        for child in affected:
            self.stdout.write(
                f" - ID={child.id} | '{child.name}' | parent='{child.parent.name if child.parent else '-'}' | active={child.is_active}"
            )

        if dry_run:
            self.stdout.write(self.style.WARNING("DRY-RUN: изменения не применены."))
            return

        changed = 0
        deleted = 0
        for child in affected:
            if delete_mode:
                child.delete()
                deleted += 1
                continue
            if child.is_active:
                child.is_active = False
                child.save(update_fields=["is_active", "updated_at"])
                changed += 1

        if delete_mode:
            self.stdout.write(self.style.SUCCESS(f"Удалено подкатегорий: {deleted}"))
        else:
            self.stdout.write(self.style.SUCCESS(f"Деактивировано подкатегорий: {changed}"))

